from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional
import uuid

app = FastAPI(title="Local Mock Server for Bedrock/Transcribe")


class InvokeRequest(BaseModel):
    modelId: Optional[str]
    body: dict


class EmbeddingRequest(BaseModel):
    text: str


class TranscribeRequest(BaseModel):
    s3_uri: str
    media_format: str


@app.post("/bedrock/invoke")
def invoke_model(req: InvokeRequest):
    msgs = req.body.get("messages") or []
    prompt = msgs[-1]["content"] if msgs else req.body.get("prompt", "")
    text = f"[mocked Claude response]\nSeeded on: {prompt[:200]}"
    return {"output": text}


@app.post("/embeddings")
def embeddings(req: EmbeddingRequest):
    vec = [0.0] * 1536
    r = abs(hash(req.text))
    for i in range(10):
        vec[(r + i) % 1536] = float(((r >> i) & 0xFF) / 255.0)
    return {"dimensions": 1536, "vector": vec}


@app.post("/transcribe/start")
def start_transcription(req: TranscribeRequest):
    job_id = str(uuid.uuid4())
    transcript = {
        "job_id": job_id,
        "status": "COMPLETED",
        "text": "This is a mocked transcript generated by the local dev server. Replace with real Transcribe in prod.",
        "timestamps": []
    }
    return transcript


@app.get("/transcribe/result/{job_id}")
def get_transcription(job_id: str):
    return {"job_id": job_id, "status": "COMPLETED", "text": "Mock transcript for job " + job_id}


@app.get("/health")
def health():
    return {"status": "ok"}
